### ISSUE TITLE
Typings for immutable-4.0.0-rc.2 not working with typescript 2.6

### ISSUE THREAD

**Issue by LarsKoelpin** [facebook/immutable-js#1298]
### What happened
When using typescript 2.6 with immutable-4.0.0-rc.2 the code does not compile.
tsc-version: 2.6.0-dev.20170830
immutable-version: 4.0.0-rc2

### Console Log
```bash
node_modules/immutable/dist/immutable-nonambient.d.ts(1871,20): error TS2430: Interface 'Stack<T>' incorrectly extends interface 'Indexed<T>'.
  Types of property 'concat' are incompatible.
    Type '<C>(...valuesOrCollections: (C | Iterable<C>)[]) => Stack<T | C>' is not assignable to type '<C>(...valuesOrCollections: (C | Iterable<C>)[]) => Indexed<T | C>'.
      Type 'Stack<T | C>' is not assignable to type 'Indexed<T | C>'.
        Types of property 'concat' are incompatible.
          Type '<C>(...valuesOrCollections: (C | Iterable<C>)[]) => Stack<T | C | C>' is not assignable to type '<C>(...valuesOrCollections: (C | Iterable<C>)[]) => Indexed<T | C | C>'.
            Type 'Stack<T | C | C>' is not assignable to type 'Indexed<T | C | C>'.
              Types of property 'flatMap' are incompatible.
                Type '<M>(mapper: (value: T | C | C, key: number, iter: Stack<T | C | C>) => M, context?: any) => Stack...' is not assignable to type '<M>(mapper: (value: T | C | C, key: number, iter: Indexed<T | C | C>) => Iterable<M>, context?: a...'.
                  Type 'Stack<Iterable<M>>' is not assignable to type 'Indexed<M>'.
                    Types of property 'toJSON' are incompatible.
                      Type '() => Iterable<M>[]' is not assignable to type '() => M[]'.
                        Type 'Iterable<M>[]' is not assignable to type 'M[]'.
                          Type 'Iterable<M>' is not assignable to type 'M'.
node_modules/immutable/dist/immutable-nonambient.d.ts(2331,22): error TS2320: Interface 'Keyed<K, V>' cannot simultaneously extend types 'Seq<K, V>' and 'Keyed<K, V>'.
  Named property 'size' of types 'Seq<K, V>' and 'Keyed<K, V>' are not identical.
node_modules/immutable/dist/immutable-nonambient.d.ts(2441,22): error TS2320: Interface 'Indexed<T>' cannot simultaneously extend types 'Seq<number, T>' and 'Indexed<T>'.
  Named property 'size' of types 'Seq<number, T>' and 'Indexed<T>' are not identical.
node_modules/immutable/dist/immutable-nonambient.d.ts(2529,22): error TS2320: Interface 'Set<T>' cannot simultaneously extend types 'Seq<T, T>' and 'Set<T>'.
  Named property 'size' of types 'Seq<T, T>' and 'Set<T>' are not identical.
node_modules/immutable/dist/immutable-nonambient.d.ts(2620,20): error TS2430: Interface 'Seq<K, V>' incorrectly extends interface 'Collection<K, V>'.
  Types of property 'map' are incompatible.
    Type '<M>(mapper: (value: V, key: K, iter: this) => M, context?: any) => Seq<K, M>' is not assignable to type '<M>(mapper: (value: V, key: K, iter: this) => M, context?: any) => Collection<K, M>'.
      Type 'Seq<K, M>' is not assignable to type 'Collection<K, M>'.
        Types of property 'filter' are incompatible.
          Type '{ <F extends M>(predicate: (value: M, key: K, iter: Seq<K, M>) => value is F, context?: any): Seq...' is not assignable to type '{ <F extends M>(predicate: (value: M, key: K, iter: Collection<K, M>) => value is F, context?: an...'.
            Type 'Seq<K, any>' is not assignable to type 'Collection<K, any>'.
              Types of property 'size' are incompatible.
                Type 'number | undefined' is not assignable to type 'number'.
                  Type 'undefined' is not assignable to type 'number'.
node_modules/immutable/dist/immutable-nonambient.d.ts(2761,22): error TS2430: Interface 'Keyed<K, V>' incorrectly extends interface 'Collection<K, V>'.
  Types of property 'toSeq' are incompatible.
    Type '() => Keyed<K, V>' is not assignable to type '() => Seq<K, V>'.
      Type 'Keyed<K, V>' is not assignable to type 'Seq<K, V>'.
        Types of property 'flatMap' are incompatible.
          Type '<KM, VM>(mapper: (value: V, key: K, iter: Keyed<K, V>) => Iterable<[KM, VM]>, context?: any) => K...' is not assignable to type '<M>(mapper: (value: V, key: K, iter: Seq<K, V>) => Iterable<M>, context?: any) => Seq<K, M>'.
            Types of parameters 'mapper' and 'mapper' are incompatible.
              Type 'Iterable<M>' is not assignable to type 'Iterable<[K, M]>'.
                Type 'M' is not assignable to type '[K, M]'.
node_modules/immutable/dist/immutable-nonambient.d.ts(2910,22): error TS2430: Interface 'Indexed<T>' incorrectly extends interface 'Collection<number, T>'.
  Types of property 'toSeq' are incompatible.
    Type '() => Indexed<T>' is not assignable to type '() => Seq<number, T>'.
      Type 'Indexed<T>' is not assignable to type 'Seq<number, T>'.
        Types of property 'filter' are incompatible.
          Type '{ <F extends T>(predicate: (value: T, index: number, iter: Indexed<T>) => value is F, context?: a...' is not assignable to type '{ <F extends T>(predicate: (value: T, key: number, iter: Seq<number, T>) => value is F, context?:...'.
            Type 'Indexed<any>' is not assignable to type 'Seq<number, any>'.
              Types of property 'concat' are incompatible.
                Type '<C>(...valuesOrCollections: (C | Iterable<C>)[]) => Indexed<any>' is not assignable to type '(...valuesOrCollections: any[]) => Collection<any, any>'.
                  Type 'Indexed<any>' is not assignable to type 'Collection<any, any>'.
                    Types of property 'map' are incompatible.
                      Type '<M>(mapper: (value: any, key: number, iter: Indexed<any>) => M, context?: any) => Indexed<M>' is not assignable to type '<M>(mapper: (value: any, key: any, iter: Collection<any, any>) => M, context?: any) => Collection...'.
                        Type 'Indexed<M>' is not assignable to type 'Collection<any, M>'.
                          Types of property 'size' are incompatible.
                            Type 'number | undefined' is not assignable to type 'number'.
                              Type 'undefined' is not assignable to type 'number'.
node_modules/immutable/dist/immutable-nonambient.d.ts(3153,22): error TS2430: Interface 'Set<T>' incorrectly extends interface 'Collection<T, T>'.
  Types of property 'toSeq' are incompatible.
    Type '() => Set<T>' is not assignable to type '() => Seq<T, T>'.
      Type 'Set<T>' is not assignable to type 'Seq<T, T>'.
        Types of property 'map' are incompatible.
          Type '<M>(mapper: (value: T, key: T, iter: Set<T>) => M, context?: any) => Set<M>' is not assignable to type '<M>(mapper: (value: T, key: T, iter: Seq<T, T>) => M, context?: any) => Seq<T, M>'.
            Type 'Set<M>' is not assignable to type 'Seq<T, M>'.
              Types of property 'map' are incompatible.
                Type '<M>(mapper: (value: M, key: M, iter: Set<M>) => M, context?: any) => Set<M>' is not assignable to type '<M>(mapper: (value: M, key: T, iter: Seq<T, M>) => M, context?: any) => Seq<T, M>'.
                  Types of parameters 'mapper' and 'mapper' are incompatible.
                    Types of parameters 'key' and 'key' are incompatible.
                      Type 'M' is not assignable to type 'T'.
```

I found a similar issue in PR #1285  which unfortunately does not do the trick for me.

### How to reproduce
I created a repository reproducing the error. This includes a custom tsconfig and an example.
https://github.com/LarsKoelpin/immutable-js-typing-error

immutable 3.8.1 works fine tho

**Comment by LarsKoelpin** [comment]
#1158
