### ISSUE TITLE
V4-- OrderedMap.concat is not a function.

### ISSUE THREAD

**Issue by randallb** [facebook/immutable-js#1418]
### What happened
In V4 RC9, using an `OrderedMap.concat` fails. I'm looking into #1373 as a potential bad merge, where `.concat` was supposed to alias `.merge` but something didn't go as planned.

### How to reproduce

Given a package.json:
```
{
  "name": "immmutable-bug-simple",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "immutable": "^4.0.0-rc.9"
  }
}
```
and an index.js of
```
const immutable = require('immutable');

const orderedMap = immutable.OrderedMap();
const orderedMap2 = immutable.OrderedMap();
orderedMap.concat(orderedMap2)
```
I get:
```
TypeError: orderedMap.concat is not a function
    at Object.<anonymous> (/Users/rb/code/experiment/immmutable-bug-simple/index.js:5:12)
```

**Comment by randallb** [comment]
I just verified the same behavior on `.map`.

```
const map = immutable.Map();
const map2 = immutable.Map();

map.concat(map2)
```

```
TypeError: map.concat is not a function
    at Object.<anonymous> (/Users/rb/code/experiment/immmutable-bug-simple/index.js:9:5)
```

**Comment by philipp-spiess** [comment]
Hi @randallb - We already have a fix for that in the master branch, it will be out with the next release :) 

https://github.com/facebook/immutable-js/pull/1402
